"""The "support the author" link, shown only outside a running mission.

The uConsole cannot open a browser, so the main menu shows the link as a QR
code to scan with a phone. The rows are generated offline by
``tools/gen_support_qr.py`` so the game needs no QR library.
"""

import pygame

from src.core.i18n import raw_text
from src.ui import layout

SUPPORT_URL = "https://buymeacoffee.com/zquu1xu570"
SUPPORT_SHORT = "buymeacoffee.com/zquu1xu570"

# --- generated by tools/gen_support_qr.py ---
QR_ROWS = (
    "11111110110001010111101111111",
    "10000010111001000010001000001",
    "10111010010100001010001011101",
    "10111010100100110100001011101",
    "10111010010100100001001011101",
    "10000010000101001011001000001",
    "11111110101010101010101111111",
    "00000000100100000111000000000",
    "10110111001001000100001001011",
    "00111000111001100111011110001",
    "10101011011011001010010000110",
    "11110000001110010011111110001",
    "01011010011000111100000001100",
    "11111100010110110011001000111",
    "11100110000001000101101100111",
    "00000000001110111010100000010",
    "01010011010100101010110011010",
    "01000101001010111010100101110",
    "10110010101011111010010110100",
    "00111100000101101111011000100",
    "01111011100001100111111111100",
    "00000000110100001000100011111",
    "11111110110110100111101011010",
    "10000010111001101010100011010",
    "10111010010010001100111110110",
    "10111010110000011110010011001",
    "10111010101011000010000100101",
    "10000010000000010000101001010",
    "11111110110110101001111100010",
)
# --- end generated ---

_CACHE = {}


def qr_surface(module_px: int, dark=(6, 14, 16), light=(214, 230, 222)) -> pygame.Surface:
    """The code with a two-module quiet zone, cached per module size."""
    key = (module_px, dark, light)
    surf = _CACHE.get(key)
    if surf is None:
        size = (len(QR_ROWS) + 4) * module_px
        surf = pygame.Surface((size, size))
        surf.fill(light)
        for y, row in enumerate(QR_ROWS):
            for x, cell in enumerate(row):
                if cell == "1":
                    surf.fill(dark, ((x + 2) * module_px, (y + 2) * module_px,
                                     module_px, module_px))
        _CACHE[key] = surf
    return surf


def draw_support_corner(surface: pygame.Surface, right: int, bottom: int,
                        color, dim_color) -> pygame.Rect:
    """QR code at a bottom-right corner, with three short lines above it."""
    code = qr_surface(3)
    rect = code.get_rect(bottomright=(right, bottom))
    surface.blit(code, rect)
    text_w = 350
    left, top = right - text_w, rect.top - 72
    layout.blit_line(surface, "menu.support.title", (left, top, text_w, 22),
                     color, size=16, align="right")
    layout.blit_line(surface, "menu.support.note", (left, top + 24, text_w, 20),
                     dim_color, size=14, align="right")
    layout.blit_line(surface, raw_text(SUPPORT_SHORT), (left, top + 46, text_w, 20),
                     dim_color, size=14, align="right")
    return rect.union(pygame.Rect(left, top, text_w, rect.top - top))
